### ISSUE TITLE
Write health check cron jobs for service availability

### ISSUE THREAD

**Issue by rocktimsaikia** [Animechan-API/animechan#108]
Write in typescript + run with `tsx` + keep in `/scripts` directory.

**Comment by jagadish-ravichandran** [comment]
Please elaborate this.

**Comment by rocktimsaikia** [comment]
This has been done. 
Related Commits: [43ab72484e7da575886fd05ae9aafe23b0ea539b](https://github.com/Animechan-API/animechan/commits/main/scripts/check-api-status.mjs)
