### ISSUE TITLE
Migration to MySQL has changed the API

### ISSUE THREAD

**Issue by kodimatrix** [Animechan-API/animechan#96]
Since issue #90, all responses now include the `id` field. However, this change, which affects backward compatibility, is not documented in the current documentation.

**Comment by melosh101** [comment]
This is intentional, and is to help with fixing typos, incorrect info and other issues with each specific quote

**Comment by rocktimsaikia** [comment]
Backward compatibility concern is valid depending on how people have coded their program to use the API. Most likely adding a new field should not break stuff but we should update the website docs for this new change. A PR is welcome for this.

**Comment by kodimatrix** [comment]
Completely agree

**Comment by kodimatrix** [comment]
take
